package mx.com.evoti.dto.bancos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1

/**
 * BancosConceptos generated by hbm2java
 */

public class BancosConceptosDto  implements java.io.Serializable {

    private static final long serialVersionUID = 4627748316689470386L;


     private int cbanId;
     private String cbanNombre;
     private String cbanTipo;
     private String cbanTabla;
     private String cbanColumnapk;

    @Override
    public String toString() {
        return  cbanId + "-" + cbanNombre ;
    }

     
    /**
     * @return the cbanId
     */
    public int getCbanId() {
        return cbanId;
    }

    /**
     * @param cbanId the cbanId to set
     */
    public void setCbanId(int cbanId) {
        this.cbanId = cbanId;
    }

    /**
     * @return the cbanNombre
     */
    public String getCbanNombre() {
        return cbanNombre;
    }

    /**
     * @param cbanNombre the cbanNombre to set
     */
    public void setCbanNombre(String cbanNombre) {
        this.cbanNombre = cbanNombre;
    }

    /**
     * @return the cbanTipo
     */
    public String getCbanTipo() {
        return cbanTipo;
    }

    /**
     * @param cbanTipo the cbanTipo to set
     */
    public void setCbanTipo(String cbanTipo) {
        this.cbanTipo = cbanTipo;
    }

    /**
     * @return the cbanTabla
     */
    public String getCbanTabla() {
        return cbanTabla;
    }

    /**
     * @param cbanTabla the cbanTabla to set
     */
    public void setCbanTabla(String cbanTabla) {
        this.cbanTabla = cbanTabla;
    }

    /**
     * @return the cbanColumnapk
     */
    public String getCbanColumnapk() {
        return cbanColumnapk;
    }

    /**
     * @param cbanColumnapk the cbanColumnapk to set
     */
    public void setCbanColumnapk(String cbanColumnapk) {
        this.cbanColumnapk = cbanColumnapk;
    }

}