package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name="pagos"
)
public class Pagos  implements java.io.Serializable {


     private Integer pagId;
     private Integer pagClaveEmpleado;
     private Date pagFecha;
     private Double pagDeposito;
     private Double pagAcumulado;
     private Integer pagEmpresa;
     private Integer pagCredito;
     private Integer pagUsuId;
     private Integer pagEstatus;
     private String pagUsuNombre;
     private Integer pagArhId;
     private Integer pagEstatusAmortizacion;
     private Integer antes7;

    public Pagos() {
    }

    public Pagos(Integer pagClaveEmpleado, Date pagFecha, Double pagDeposito, Double pagAcumulado, Integer pagEmpresa, Integer pagCredito, Integer pagUsuId, Integer pagEstatus, String pagUsuNombre, Integer pagArhId, Integer pagEstatusAmortizacion, Integer antes7) {
       this.pagClaveEmpleado = pagClaveEmpleado;
       this.pagFecha = pagFecha;
       this.pagDeposito = pagDeposito;
       this.pagAcumulado = pagAcumulado;
       this.pagEmpresa = pagEmpresa;
       this.pagCredito = pagCredito;
       this.pagUsuId = pagUsuId;
       this.pagEstatus = pagEstatus;
       this.pagUsuNombre = pagUsuNombre;
       this.pagArhId = pagArhId;
       this.pagEstatusAmortizacion = pagEstatusAmortizacion;
       this.antes7 = antes7;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="pag_id", nullable=false)
    public Integer getPagId() {
        return this.pagId;
    }
    
    public void setPagId(Integer pagId) {
        this.pagId = pagId;
    }

    
    @Column(name="pag_clave_empleado")
    public Integer getPagClaveEmpleado() {
        return this.pagClaveEmpleado;
    }
    
    public void setPagClaveEmpleado(Integer pagClaveEmpleado) {
        this.pagClaveEmpleado = pagClaveEmpleado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="pag_fecha", length=10)
    public Date getPagFecha() {
        return this.pagFecha;
    }
    
    public void setPagFecha(Date pagFecha) {
        this.pagFecha = pagFecha;
    }

    
    @Column(name="pag_deposito", precision=22, scale=0)
    public Double getPagDeposito() {
        return this.pagDeposito;
    }
    
    public void setPagDeposito(Double pagDeposito) {
        this.pagDeposito = pagDeposito;
    }

    
    @Column(name="pag_acumulado", precision=22, scale=0)
    public Double getPagAcumulado() {
        return this.pagAcumulado;
    }
    
    public void setPagAcumulado(Double pagAcumulado) {
        this.pagAcumulado = pagAcumulado;
    }

    
    @Column(name="pag_empresa")
    public Integer getPagEmpresa() {
        return this.pagEmpresa;
    }
    
    public void setPagEmpresa(Integer pagEmpresa) {
        this.pagEmpresa = pagEmpresa;
    }

    
    @Column(name="pag_credito")
    public Integer getPagCredito() {
        return this.pagCredito;
    }
    
    public void setPagCredito(Integer pagCredito) {
        this.pagCredito = pagCredito;
    }

    
    @Column(name="pag_usu_id")
    public Integer getPagUsuId() {
        return this.pagUsuId;
    }
    
    public void setPagUsuId(Integer pagUsuId) {
        this.pagUsuId = pagUsuId;
    }

    
    @Column(name="pag_estatus")
    public Integer getPagEstatus() {
        return this.pagEstatus;
    }
    
    public void setPagEstatus(Integer pagEstatus) {
        this.pagEstatus = pagEstatus;
    }

    
    @Column(name="pag_usu_nombre", length=200)
    public String getPagUsuNombre() {
        return this.pagUsuNombre;
    }
    
    public void setPagUsuNombre(String pagUsuNombre) {
        this.pagUsuNombre = pagUsuNombre;
    }

    
    @Column(name="pag_arh_id")
    public Integer getPagArhId() {
        return this.pagArhId;
    }
    
    public void setPagArhId(Integer pagArhId) {
        this.pagArhId = pagArhId;
    }

    
    @Column(name="pag_estatus_amortizacion")
    public Integer getPagEstatusAmortizacion() {
        return this.pagEstatusAmortizacion;
    }
    
    public void setPagEstatusAmortizacion(Integer pagEstatusAmortizacion) {
        this.pagEstatusAmortizacion = pagEstatusAmortizacion;
    }

    
    @Column(name="antes7")
    public Integer getAntes7() {
        return this.antes7;
    }
    
    public void setAntes7(Integer antes7) {
        this.antes7 = antes7;
    }




}


