package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolicitudAvales generated by hbm2java
 */
@Entity
@Table(name="solicitud_avales"
)
public class SolicitudAvales  implements java.io.Serializable {


     private Integer idSolAva;
     private Solicitudes solicitudes;
     private Integer solAvaClaveEmpleado;
     private Integer solAvaCredito;
     private Integer solAvaIdEmpleado;
     private Integer solAvaEstatus;

    public SolicitudAvales() {
    }

    public SolicitudAvales(Solicitudes solicitudes, Integer solAvaClaveEmpleado, Integer solAvaCredito, Integer solAvaIdEmpleado, Integer solAvaEstatus) {
       this.solicitudes = solicitudes;
       this.solAvaClaveEmpleado = solAvaClaveEmpleado;
       this.solAvaCredito = solAvaCredito;
       this.solAvaIdEmpleado = solAvaIdEmpleado;
       this.solAvaEstatus = solAvaEstatus;
    }
    public SolicitudAvales(Solicitudes solicitud, int estatus) {
       this.solicitudes = solicitud;
       this.solAvaEstatus = estatus;

    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_sol_ava", nullable=false)
    public Integer getIdSolAva() {
        return this.idSolAva;
    }
    
    public void setIdSolAva(Integer idSolAva) {
        this.idSolAva = idSolAva;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sol_ava_solicitud")
    public Solicitudes getSolicitudes() {
        return this.solicitudes;
    }
    
    public void setSolicitudes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }

    
    @Column(name="sol_ava_clave_empleado")
    public Integer getSolAvaClaveEmpleado() {
        return this.solAvaClaveEmpleado;
    }
    
    public void setSolAvaClaveEmpleado(Integer solAvaClaveEmpleado) {
        this.solAvaClaveEmpleado = solAvaClaveEmpleado;
    }

    
    @Column(name="sol_ava_credito")
    public Integer getSolAvaCredito() {
        return this.solAvaCredito;
    }
    
    public void setSolAvaCredito(Integer solAvaCredito) {
        this.solAvaCredito = solAvaCredito;
    }

    
    @Column(name="sol_ava_id_empleado")
    public Integer getSolAvaIdEmpleado() {
        return this.solAvaIdEmpleado;
    }
    
    public void setSolAvaIdEmpleado(Integer solAvaIdEmpleado) {
        this.solAvaIdEmpleado = solAvaIdEmpleado;
    }

    
    @Column(name="sol_ava_estatus")
    public Integer getSolAvaEstatus() {
        return this.solAvaEstatus;
    }
    
    public void setSolAvaEstatus(Integer solAvaEstatus) {
        this.solAvaEstatus = solAvaEstatus;
    }




}


