package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Amortizacion generated by hbm2java
 */
@Entity
@Table(name="amortizacion"
)
public class Amortizacion  implements java.io.Serializable {


     private Integer amoId;
     private CreditosFinal creditosFinal;
     private Integer amoNumeroPago;
     private Double amoCapital;
     private Double amoAmortizacion;
     private Double amoInteres;
     private Double amoIva;
     private Double amoMontoPago;
     private Long amoSolicitud;
     private Double amoSaldo;
     private Date amoFechaPago;
     private String amoEstatus;
     private Integer amoClaveEmpleado;
     private Integer amoPagoId;
     private Integer amoUsuId;
     private Integer amoProducto;
     private Integer amoEstatusInt;

    public Amortizacion() {
    }

    public Amortizacion(CreditosFinal creditosFinal, Integer amoNumeroPago, Double amoCapital, Double amoAmortizacion, Double amoInteres, Double amoIva, Double amoMontoPago, Long amoSolicitud, Double amoSaldo, Date amoFechaPago, String amoEstatus, Integer amoClaveEmpleado, Integer amoPagoId, Integer amoUsuId, Integer amoProducto, Integer amoEstatus2) {
       this.creditosFinal = creditosFinal;
       this.amoNumeroPago = amoNumeroPago;
       this.amoCapital = amoCapital;
       this.amoAmortizacion = amoAmortizacion;
       this.amoInteres = amoInteres;
       this.amoIva = amoIva;
       this.amoMontoPago = amoMontoPago;
       this.amoSolicitud = amoSolicitud;
       this.amoSaldo = amoSaldo;
       this.amoFechaPago = amoFechaPago;
       this.amoEstatus = amoEstatus;
       this.amoClaveEmpleado = amoClaveEmpleado;
       this.amoPagoId = amoPagoId;
       this.amoUsuId = amoUsuId;
       this.amoProducto = amoProducto;
       this.amoEstatusInt = amoEstatus2;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="amo_id", nullable=false)
    public Integer getAmoId() {
        return this.amoId;
    }
    
    public void setAmoId(Integer amoId) {
        this.amoId = amoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="amo_credito")
    public CreditosFinal getCreditosFinal() {
        return this.creditosFinal;
    }
    
    public void setCreditosFinal(CreditosFinal creditosFinal) {
        this.creditosFinal = creditosFinal;
    }

    
    @Column(name="amo_numero_pago")
    public Integer getAmoNumeroPago() {
        return this.amoNumeroPago;
    }
    
    public void setAmoNumeroPago(Integer amoNumeroPago) {
        this.amoNumeroPago = amoNumeroPago;
    }

    
    @Column(name="amo_capital", precision=22, scale=0)
    public Double getAmoCapital() {
        return this.amoCapital;
    }
    
    public void setAmoCapital(Double amoCapital) {
        this.amoCapital = amoCapital;
    }

    
    @Column(name="amo_amortizacion", precision=22, scale=0)
    public Double getAmoAmortizacion() {
        return this.amoAmortizacion;
    }
    
    public void setAmoAmortizacion(Double amoAmortizacion) {
        this.amoAmortizacion = amoAmortizacion;
    }

    
    @Column(name="amo_interes", precision=22, scale=0)
    public Double getAmoInteres() {
        return this.amoInteres;
    }
    
    public void setAmoInteres(Double amoInteres) {
        this.amoInteres = amoInteres;
    }

    
    @Column(name="amo_iva", precision=22, scale=0)
    public Double getAmoIva() {
        return this.amoIva;
    }
    
    public void setAmoIva(Double amoIva) {
        this.amoIva = amoIva;
    }

    
    @Column(name="amo_monto_pago", precision=22, scale=0)
    public Double getAmoMontoPago() {
        return this.amoMontoPago;
    }
    
    public void setAmoMontoPago(Double amoMontoPago) {
        this.amoMontoPago = amoMontoPago;
    }

    
    @Column(name="amo_solicitud")
    public Long getAmoSolicitud() {
        return this.amoSolicitud;
    }
    
    public void setAmoSolicitud(Long amoSolicitud) {
        this.amoSolicitud = amoSolicitud;
    }

    
    @Column(name="amo_saldo", precision=22, scale=0)
    public Double getAmoSaldo() {
        return this.amoSaldo;
    }
    
    public void setAmoSaldo(Double amoSaldo) {
        this.amoSaldo = amoSaldo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="amo_fecha_pago", length=10)
    public Date getAmoFechaPago() {
        return this.amoFechaPago;
    }
    
    public void setAmoFechaPago(Date amoFechaPago) {
        this.amoFechaPago = amoFechaPago;
    }

    
    @Column(name="amo_estatus", length=20)
    public String getAmoEstatus() {
        return this.amoEstatus;
    }
    
    public void setAmoEstatus(String amoEstatus) {
        this.amoEstatus = amoEstatus;
    }

    
    @Column(name="amo_clave_empleado")
    public Integer getAmoClaveEmpleado() {
        return this.amoClaveEmpleado;
    }
    
    public void setAmoClaveEmpleado(Integer amoClaveEmpleado) {
        this.amoClaveEmpleado = amoClaveEmpleado;
    }

    
    @Column(name="amo_pago_id")
    public Integer getAmoPagoId() {
        return this.amoPagoId;
    }
    
    public void setAmoPagoId(Integer amoPagoId) {
        this.amoPagoId = amoPagoId;
    }

    
    @Column(name="amo_usu_id")
    public Integer getAmoUsuId() {
        return this.amoUsuId;
    }
    
    public void setAmoUsuId(Integer amoUsuId) {
        this.amoUsuId = amoUsuId;
    }

    
    @Column(name="amo_producto")
    public Integer getAmoProducto() {
        return this.amoProducto;
    }
    
    public void setAmoProducto(Integer amoProducto) {
        this.amoProducto = amoProducto;
    }

    
    
    /**
     * @return the amoEstatusInt
     */
     @Column(name="amo_estatus_int")
    public Integer getAmoEstatusInt() {
        return amoEstatusInt;
    }

    /**
     * @param amoEstatusInt the amoEstatusInt to set
     */
    public void setAmoEstatusInt(Integer amoEstatusInt) {
        this.amoEstatusInt = amoEstatusInt;
    }




}


