package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchivosHistorial generated by hbm2java
 */
@Entity
@Table(name="archivos_historial"
)
public class ArchivosHistorial  implements java.io.Serializable {


     private Integer arhId;
     private String arhNombreArchivo;
     private Date arhFechaSubida;
     private Integer arhEmpresa;
     private Integer arhEstatus;
     private Integer arhRegistros;
     private Integer arhTipoArchivo;
     private Date arhFechaCatorcena;

    public ArchivosHistorial() {
    }

    public ArchivosHistorial(String arhNombreArchivo, Date arhFechaSubida, Integer arhEmpresa, Integer arhEstatus, Integer arhRegistros, Integer arhTipoArchivo, Date arhFechaCatorcena) {
       this.arhNombreArchivo = arhNombreArchivo;
       this.arhFechaSubida = arhFechaSubida;
       this.arhEmpresa = arhEmpresa;
       this.arhEstatus = arhEstatus;
       this.arhRegistros = arhRegistros;
       this.arhTipoArchivo = arhTipoArchivo;
       this.arhFechaCatorcena = arhFechaCatorcena;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="arh_id", nullable=false)
    public Integer getArhId() {
        return this.arhId;
    }
    
    public void setArhId(Integer arhId) {
        this.arhId = arhId;
    }

    
    @Column(name="arh_nombre_archivo", length=500)
    public String getArhNombreArchivo() {
        return this.arhNombreArchivo;
    }
    
    public void setArhNombreArchivo(String arhNombreArchivo) {
        this.arhNombreArchivo = arhNombreArchivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="arh_fecha_subida", length=10)
    public Date getArhFechaSubida() {
        return this.arhFechaSubida;
    }
    
    public void setArhFechaSubida(Date arhFechaSubida) {
        this.arhFechaSubida = arhFechaSubida;
    }

    
    @Column(name="arh_empresa")
    public Integer getArhEmpresa() {
        return this.arhEmpresa;
    }
    
    public void setArhEmpresa(Integer arhEmpresa) {
        this.arhEmpresa = arhEmpresa;
    }

    
    @Column(name="arh_estatus")
    public Integer getArhEstatus() {
        return this.arhEstatus;
    }
    
    public void setArhEstatus(Integer arhEstatus) {
        this.arhEstatus = arhEstatus;
    }

    
    @Column(name="arh_registros")
    public Integer getArhRegistros() {
        return this.arhRegistros;
    }
    
    public void setArhRegistros(Integer arhRegistros) {
        this.arhRegistros = arhRegistros;
    }

    
    @Column(name="arh_tipo_archivo")
    public Integer getArhTipoArchivo() {
        return this.arhTipoArchivo;
    }
    
    public void setArhTipoArchivo(Integer arhTipoArchivo) {
        this.arhTipoArchivo = arhTipoArchivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="arh_fecha_catorcena", length=10)
    public Date getArhFechaCatorcena() {
        return this.arhFechaCatorcena;
    }
    
    public void setArhFechaCatorcena(Date arhFechaCatorcena) {
        this.arhFechaCatorcena = arhFechaCatorcena;
    }




}


