package mx.com.evoti.hibernate.pojos;
// Generated 27/06/2017 11:55:25 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RelBancoEdocta generated by hbm2java
 */
@Entity
@Table(name="rel_banco_edocta"
    ,catalog="sindicato"
)
public class RelBancoEdocta  implements java.io.Serializable {


     private RelBancoEdoctaId id;
     private Date rbeFechaRel;

    public RelBancoEdocta() {
    }

	
    public RelBancoEdocta(RelBancoEdoctaId id) {
        this.id = id;
    }
    public RelBancoEdocta(RelBancoEdoctaId id, Date rbeFechaRel) {
       this.id = id;
       this.rbeFechaRel = rbeFechaRel;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="rbeId", column=@Column(name="rbe_id", nullable=false) ), 
        @AttributeOverride(name="rbeIdBancoEc", column=@Column(name="rbe_id_banco_ec", nullable=false) ), 
        @AttributeOverride(name="rbeTipo", column=@Column(name="rbe_tipo", nullable=false) ) } )
    public RelBancoEdoctaId getId() {
        return this.id;
    }
    
    public void setId(RelBancoEdoctaId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rbe_fecha_rel", length=10)
    public Date getRbeFechaRel() {
        return this.rbeFechaRel;
    }
    
    public void setRbeFechaRel(Date rbeFechaRel) {
        this.rbeFechaRel = rbeFechaRel;
    }




}


