package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;


/**
 * Empresas generated by hbm2java
 */
@Entity
@Table(name="empresas"
)
public class Empresas  implements java.io.Serializable {


     private Integer empId;
     private String empDescripcion;
     private String empAbreviacion;
     private String empRfc;
     private String empTelefono;
     private String empDireccion;
     private Set<Usuarios> usuarios = new HashSet<>(0);

    public Empresas() {
    }

	
    public Empresas(int empId) {
        this.empId = empId;
    }
    
    
    public Empresas(int empId, String empDescripcion, String empAbreviacion, String empRfc, String empTelefono, String empDireccion) {
       this.empId = empId;
       this.empDescripcion = empDescripcion;
       this.empAbreviacion = empAbreviacion;
       this.empRfc = empRfc;
       this.empTelefono = empTelefono;
       this.empDireccion = empDireccion;
       
    }
    public Empresas(int empId, String empDescripcion, String empAbreviacion, String empRfc, String empTelefono, String empDireccion, Set<Usuarios> usuarios) {
       this.empId = empId;
       this.empDescripcion = empDescripcion;
       this.empAbreviacion = empAbreviacion;
       this.empRfc = empRfc;
       this.empTelefono = empTelefono;
       this.empDireccion = empDireccion;
       this.usuarios = usuarios;
    }
    
   
     @Id 
    @Column(name="emp_id", nullable=false)
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    
    @Column(name="emp_descripcion", length=50)
    public String getEmpDescripcion() {
        return this.empDescripcion;
    }
    
    public void setEmpDescripcion(String empDescripcion) {
        this.empDescripcion = empDescripcion;
    }

    
    @Column(name="emp_abreviacion", length=20)
    public String getEmpAbreviacion() {
        return this.empAbreviacion;
    }
    
    public void setEmpAbreviacion(String empAbreviacion) {
        this.empAbreviacion = empAbreviacion;
    }

    
    @Column(name="emp_rfc", length=20)
    public String getEmpRfc() {
        return this.empRfc;
    }
    
    public void setEmpRfc(String empRfc) {
        this.empRfc = empRfc;
    }

    
    @Column(name="emp_telefono", length=20)
    public String getEmpTelefono() {
        return this.empTelefono;
    }
    
    public void setEmpTelefono(String empTelefono) {
        this.empTelefono = empTelefono;
    }

    
    @Column(name="emp_direccion", length=200)
    public String getEmpDireccion() {
        return this.empDireccion;
    }
    
    public void setEmpDireccion(String empDireccion) {
        this.empDireccion = empDireccion;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="empresas")
@Fetch(FetchMode.SELECT)
    public Set<Usuarios> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuarios> usuarios) {
        this.usuarios = usuarios;
    }

    @Override
    public String toString() {
        return "Empresas{" + "empId=" + empId + ", empDescripcion=" + empDescripcion + ", empAbreviacion=" + empAbreviacion + ", empRfc=" + empRfc + ", empTelefono=" + empTelefono + ", empDireccion=" + empDireccion + '}';
    }

   

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + this.empId;
        hash = 37 * hash + Objects.hashCode(this.empAbreviacion);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Empresas other = (Empresas) obj;
        if (!Objects.equals(this.empId, other.empId)) {
            return false;
        }
        return Objects.equals(this.empAbreviacion, other.empAbreviacion);
    }




}


