package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmortizacionEstatus generated by hbm2java
 */
@Entity
@Table(name="amortizacion_estatus"
)
public class AmortizacionEstatus  implements java.io.Serializable {


     private Integer amoEstId;
     private String amoEstNombre;
     private String amoEstDescripcion;

    public AmortizacionEstatus() {
    }

    public AmortizacionEstatus(String amoEstNombre, String amoEstDescripcion) {
       this.amoEstNombre = amoEstNombre;
       this.amoEstDescripcion = amoEstDescripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="amo_est_id", unique=true, nullable=false)
    public Integer getAmoEstId() {
        return this.amoEstId;
    }
    
    public void setAmoEstId(Integer amoEstId) {
        this.amoEstId = amoEstId;
    }

    
    @Column(name="amo_est_nombre", nullable=false, length=40)
    public String getAmoEstNombre() {
        return this.amoEstNombre;
    }
    
    public void setAmoEstNombre(String amoEstNombre) {
        this.amoEstNombre = amoEstNombre;
    }

    
    @Column(name="amo_est_descripcion", nullable=false, length=200)
    public String getAmoEstDescripcion() {
        return this.amoEstDescripcion;
    }
    
    public void setAmoEstDescripcion(String amoEstDescripcion) {
        this.amoEstDescripcion = amoEstDescripcion;
    }




}


