package mx.com.evoti.hibernate.pojos;
// Generated 27/03/2017 05:12:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BancoEdocta generated by hbm2java
 */
@Entity
@Table(name="banco_edocta"
)
public class BancoEdocta  implements java.io.Serializable {


     private BancoEdoctaId id;
     private Date becFechaTransaccion;

    public BancoEdocta() {
    }

	
    public BancoEdocta(BancoEdoctaId id) {
        this.id = id;
    }
    public BancoEdocta(BancoEdoctaId id, Date becFechaTransaccion) {
       this.id = id;
       this.becFechaTransaccion = becFechaTransaccion;
    }
   
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="becIdBanco", column=@Column(name="bec_id_banco", nullable=false) ), 
        @AttributeOverride(name="becIdEdocta", column=@Column(name="bec_id_edocta", nullable=false) ) } )
    public BancoEdoctaId getId() {
        return this.id;
    }
    
    public void setId(BancoEdoctaId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bec_fecha_transaccion", length=10)
    public Date getBecFechaTransaccion() {
        return this.becFechaTransaccion;
    }
    
    public void setBecFechaTransaccion(Date becFechaTransaccion) {
        this.becFechaTransaccion = becFechaTransaccion;
    }




}


