package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BancosConceptos generated by hbm2java
 */
@Entity
@Table(name="bancos_conceptos"
)
public class BancosConceptos  implements java.io.Serializable {


     private int cbanId;
     private String cbanNombre;
     private String cbanTipo;
     private String cbanTabla;
     private String cbanColumnapk;

    public BancosConceptos() {
    }

	
    public BancosConceptos(int cbanId) {
        this.cbanId = cbanId;
    }
    public BancosConceptos(int cbanId, String cbanNombre, String cbanTipo, String cbanTabla, String cbanColumnapk) {
       this.cbanId = cbanId;
       this.cbanNombre = cbanNombre;
       this.cbanTipo = cbanTipo;
       this.cbanTabla = cbanTabla;
       this.cbanColumnapk = cbanColumnapk;
    }
   
     @Id 

    
    @Column(name="cban_id", nullable=false)
    public int getCbanId() {
        return this.cbanId;
    }
    
    public void setCbanId(int cbanId) {
        this.cbanId = cbanId;
    }

    
    @Column(name="cban_nombre", length=40)
    public String getCbanNombre() {
        return this.cbanNombre;
    }
    
    public void setCbanNombre(String cbanNombre) {
        this.cbanNombre = cbanNombre;
    }

    
    @Column(name="cban_tipo", length=20)
    public String getCbanTipo() {
        return this.cbanTipo;
    }
    
    public void setCbanTipo(String cbanTipo) {
        this.cbanTipo = cbanTipo;
    }

    
    @Column(name="cban_tabla", length=20)
    public String getCbanTabla() {
        return this.cbanTabla;
    }
    
    public void setCbanTabla(String cbanTabla) {
        this.cbanTabla = cbanTabla;
    }

    
    @Column(name="cban_columnapk", length=50)
    public String getCbanColumnapk() {
        return this.cbanColumnapk;
    }
    
    public void setCbanColumnapk(String cbanColumnapk) {
        this.cbanColumnapk = cbanColumnapk;
    }




}


