package mx.com.evoti.hibernate.pojos;
// Generated 1/02/2017 05:08:41 PM by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Beneficiarios generated by hbm2java
 */
@Entity
@Table(name = "beneficiarios"
)
public class Beneficiarios implements java.io.Serializable {

    private Integer benId;
   
    private String benNombre;
    private String benPaterno;
    private String benMaterno;
    private Integer benParentesco;
    private Double benPct;
    private String benDireccion;
    private String benTelefono;
    private String benCelular;
    private Integer benUsuId;

    public Beneficiarios() {
    }

    public Beneficiarios(String benNombre, String benPaterno, String benMaterno, Integer benParentesco, Double benPct, String benDireccion, String benTelefono, String benCelular, Integer benUsuId) {
      
        this.benNombre = benNombre;
        this.benPaterno = benPaterno;
        this.benMaterno = benMaterno;
        this.benParentesco = benParentesco;
        this.benPct = benPct;
        this.benDireccion = benDireccion;
        this.benTelefono = benTelefono;
        this.benCelular = benCelular;
        this.benUsuId = benUsuId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ben_id", unique = true, nullable = false)
    public Integer getBenId() {
        return this.benId;
    }

    public void setBenId(Integer benId) {
        this.benId = benId;
    }

   

    @Column(name = "ben_nombre", length = 50)
    public String getBenNombre() {
        return this.benNombre;
    }

    public void setBenNombre(String benNombre) {
        this.benNombre = benNombre;
    }

    @Column(name = "ben_paterno", length = 50)
    public String getBenPaterno() {
        return this.benPaterno;
    }

    public void setBenPaterno(String benPaterno) {
        this.benPaterno = benPaterno;
    }

    @Column(name = "ben_materno", length = 50)
    public String getBenMaterno() {
        return this.benMaterno;
    }

    public void setBenMaterno(String benMaterno) {
        this.benMaterno = benMaterno;
    }

    @Column(name = "ben_parentesco")
    public Integer getBenParentesco() {
        return this.benParentesco;
    }

    public void setBenParentesco(Integer benParentesco) {
        this.benParentesco = benParentesco;
    }

    @Column(name = "ben_pct", precision = 22, scale = 0)
    public Double getBenPct() {
        return this.benPct;
    }

    public void setBenPct(Double benPct) {
        this.benPct = benPct;
    }

    @Column(name = "ben_direccion", length = 100)
    public String getBenDireccion() {
        return this.benDireccion;
    }

    public void setBenDireccion(String benDireccion) {
        this.benDireccion = benDireccion;
    }

    @Column(name = "ben_telefono", length = 20)
    public String getBenTelefono() {
        return this.benTelefono;
    }

    public void setBenTelefono(String benTelefono) {
        this.benTelefono = benTelefono;
    }

    @Column(name = "ben_celular", length = 20)
    public String getBenCelular() {
        return this.benCelular;
    }

    public void setBenCelular(String benCelular) {
        this.benCelular = benCelular;
    }

    @Column(name = "ben_usu_id")
    public Integer getBenUsuId() {
        return this.benUsuId;
    }

    public void setBenUsuId(Integer benUsuId) {
        this.benUsuId = benUsuId;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 37 * hash + Objects.hashCode(this.benId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Beneficiarios other = (Beneficiarios) obj;
        return Objects.equals(this.benId, other.benId);
    }

}
