package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cargos generated by hbm2java
 */
@Entity
@Table(name="cargos"
)
public class Cargos  implements java.io.Serializable {


     private Integer idCargo;
     private Integer carCredito;
     private Integer carNumeroPago;
     private Integer carCatorcenas;
     private Double carSaldo;
     private Double carAmortizacion;
     private Double carInteres;
     private Double carPago;
     private Date carFecha;
     private Double carSaldoActual;

    public Cargos() {
    }

    public Cargos(Integer carCredito, Integer carNumeroPago, Integer carCatorcenas, Double carSaldo, Double carAmortizacion, Double carInteres, Double carPago, Date carFecha, Double carSaldoActual) {
       this.carCredito = carCredito;
       this.carNumeroPago = carNumeroPago;
       this.carCatorcenas = carCatorcenas;
       this.carSaldo = carSaldo;
       this.carAmortizacion = carAmortizacion;
       this.carInteres = carInteres;
       this.carPago = carPago;
       this.carFecha = carFecha;
       this.carSaldoActual = carSaldoActual;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cargo", nullable=false)
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }

    
    @Column(name="car_credito")
    public Integer getCarCredito() {
        return this.carCredito;
    }
    
    public void setCarCredito(Integer carCredito) {
        this.carCredito = carCredito;
    }

    
    @Column(name="car_numero_pago")
    public Integer getCarNumeroPago() {
        return this.carNumeroPago;
    }
    
    public void setCarNumeroPago(Integer carNumeroPago) {
        this.carNumeroPago = carNumeroPago;
    }

    
    @Column(name="car_catorcenas")
    public Integer getCarCatorcenas() {
        return this.carCatorcenas;
    }
    
    public void setCarCatorcenas(Integer carCatorcenas) {
        this.carCatorcenas = carCatorcenas;
    }

    
    @Column(name="car_saldo", precision=22, scale=0)
    public Double getCarSaldo() {
        return this.carSaldo;
    }
    
    public void setCarSaldo(Double carSaldo) {
        this.carSaldo = carSaldo;
    }

    
    @Column(name="car_amortizacion", precision=22, scale=0)
    public Double getCarAmortizacion() {
        return this.carAmortizacion;
    }
    
    public void setCarAmortizacion(Double carAmortizacion) {
        this.carAmortizacion = carAmortizacion;
    }

    
    @Column(name="car_interes", precision=22, scale=0)
    public Double getCarInteres() {
        return this.carInteres;
    }
    
    public void setCarInteres(Double carInteres) {
        this.carInteres = carInteres;
    }

    
    @Column(name="car_pago", precision=22, scale=0)
    public Double getCarPago() {
        return this.carPago;
    }
    
    public void setCarPago(Double carPago) {
        this.carPago = carPago;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="car_fecha", length=10)
    public Date getCarFecha() {
        return this.carFecha;
    }
    
    public void setCarFecha(Date carFecha) {
        this.carFecha = carFecha;
    }

    
    @Column(name="car_saldo_actual", precision=22, scale=0)
    public Double getCarSaldoActual() {
        return this.carSaldoActual;
    }
    
    public void setCarSaldoActual(Double carSaldoActual) {
        this.carSaldoActual = carSaldoActual;
    }




}


