package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Catorcenas generated by hbm2java
 */
@Entity
@Table(name="catorcenas"
)
public class Catorcenas  implements java.io.Serializable {


     private int carId;
     private Date carFecha;
     private Integer carDia;
     private Integer carMes;
     private Integer carAnio;
     private Integer carInversiones;

    public Catorcenas() {
    }

	
    public Catorcenas(int carId) {
        this.carId = carId;
    }
    public Catorcenas(int carId, Date carFecha, Integer carDia, Integer carMes, Integer carAnio, Integer carInversiones) {
       this.carId = carId;
       this.carFecha = carFecha;
       this.carDia = carDia;
       this.carMes = carMes;
       this.carAnio = carAnio;
       this.carInversiones = carInversiones;
    }
   
     @Id 

    
    @Column(name="car_id", nullable=false)
    public int getCarId() {
        return this.carId;
    }
    
    public void setCarId(int carId) {
        this.carId = carId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="car_fecha", length=10)
    public Date getCarFecha() {
        return this.carFecha;
    }
    
    public void setCarFecha(Date carFecha) {
        this.carFecha = carFecha;
    }

    
    @Column(name="car_dia")
    public Integer getCarDia() {
        return this.carDia;
    }
    
    public void setCarDia(Integer carDia) {
        this.carDia = carDia;
    }

    
    @Column(name="car_mes")
    public Integer getCarMes() {
        return this.carMes;
    }
    
    public void setCarMes(Integer carMes) {
        this.carMes = carMes;
    }

    
    @Column(name="car_anio")
    public Integer getCarAnio() {
        return this.carAnio;
    }
    
    public void setCarAnio(Integer carAnio) {
        this.carAnio = carAnio;
    }

    
    @Column(name="car_inversiones")
    public Integer getCarInversiones() {
        return this.carInversiones;
    }
    
    public void setCarInversiones(Integer carInversiones) {
        this.carInversiones = carInversiones;
    }




}


