package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Creditos generated by hbm2java
 */
@Entity
@Table(name="creditos"
)
public class Creditos  implements java.io.Serializable {


     private int creId;
     private String creClaveCredito;
     private Double crePrestamos;
     private Integer crePagos;
     private Date creFechaInicio;
     private Date creFechaTermino;
     private Integer creProspecto;
     private Integer creClaveEmpleado;
     private String creFondeo;
     private String creFondeador;

    public Creditos() {
    }

	
    public Creditos(int creId) {
        this.creId = creId;
    }
    public Creditos(int creId, String creClaveCredito, Double crePrestamos, Integer crePagos, Date creFechaInicio, Date creFechaTermino, Integer creProspecto, Integer creClaveEmpleado, String creFondeo, String creFondeador) {
       this.creId = creId;
       this.creClaveCredito = creClaveCredito;
       this.crePrestamos = crePrestamos;
       this.crePagos = crePagos;
       this.creFechaInicio = creFechaInicio;
       this.creFechaTermino = creFechaTermino;
       this.creProspecto = creProspecto;
       this.creClaveEmpleado = creClaveEmpleado;
       this.creFondeo = creFondeo;
       this.creFondeador = creFondeador;
    }
   
     @Id 

    
    @Column(name="cre_id", nullable=false)
    public int getCreId() {
        return this.creId;
    }
    
    public void setCreId(int creId) {
        this.creId = creId;
    }

    
    @Column(name="cre_clave_credito", length=30)
    public String getCreClaveCredito() {
        return this.creClaveCredito;
    }
    
    public void setCreClaveCredito(String creClaveCredito) {
        this.creClaveCredito = creClaveCredito;
    }

    
    @Column(name="cre_prestamos", precision=22, scale=0)
    public Double getCrePrestamos() {
        return this.crePrestamos;
    }
    
    public void setCrePrestamos(Double crePrestamos) {
        this.crePrestamos = crePrestamos;
    }

    
    @Column(name="cre_pagos")
    public Integer getCrePagos() {
        return this.crePagos;
    }
    
    public void setCrePagos(Integer crePagos) {
        this.crePagos = crePagos;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cre_fecha_inicio", length=10)
    public Date getCreFechaInicio() {
        return this.creFechaInicio;
    }
    
    public void setCreFechaInicio(Date creFechaInicio) {
        this.creFechaInicio = creFechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cre_fecha_termino", length=10)
    public Date getCreFechaTermino() {
        return this.creFechaTermino;
    }
    
    public void setCreFechaTermino(Date creFechaTermino) {
        this.creFechaTermino = creFechaTermino;
    }

    
    @Column(name="cre_prospecto")
    public Integer getCreProspecto() {
        return this.creProspecto;
    }
    
    public void setCreProspecto(Integer creProspecto) {
        this.creProspecto = creProspecto;
    }

    
    @Column(name="cre_clave_empleado")
    public Integer getCreClaveEmpleado() {
        return this.creClaveEmpleado;
    }
    
    public void setCreClaveEmpleado(Integer creClaveEmpleado) {
        this.creClaveEmpleado = creClaveEmpleado;
    }

    
    @Column(name="cre_fondeo", length=20)
    public String getCreFondeo() {
        return this.creFondeo;
    }
    
    public void setCreFondeo(String creFondeo) {
        this.creFondeo = creFondeo;
    }

    
    @Column(name="cre_fondeador", length=40)
    public String getCreFondeador() {
        return this.creFondeador;
    }
    
    public void setCreFondeador(String creFondeador) {
        this.creFondeador = creFondeador;
    }




}


