package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CreditosFinal generated by hbm2java
 */
@Entity
@Table(name="creditos_final"
)
public class CreditosFinal  implements java.io.Serializable {


     private Integer creId;
     private Date creFechaDeposito;
     private String creEmpresa;
     private String creNombre;
     private String creTipo;
     private Double crePrestamo;
     private Integer creCatorcenas;
     private Date creFechaPrimerPago;
     private Date creFechaIncobrable;
     private Integer creClaveEmpleado;
     private Integer creProducto;
     private Long creSolicitud;
     private Double crePagoQuincenal;
     private Double creSaldo;
     private String creClave;
     private Integer creEstatus;
     private Integer creUsuId;
     private Integer crePadre;
     private Date creFechaNuevoMonto;
     private Set<Amortizacion> amortizacions = new HashSet<Amortizacion>(0);

    public CreditosFinal() {
    }

    public CreditosFinal(Integer creId, Date creFechaDeposito, String creEmpresa, String creNombre, String creTipo, Double crePrestamo, Integer creCatorcenas, Date creFechaPrimerPago, Date creFechaIncobrable, Integer creClaveEmpleado, Integer creProducto, Long creSolicitud, Double crePagoQuincenal, Double creSaldo, String creClave, Integer creEstatus, Integer creUsuId, Integer crePadre, Date creFechaNuevoMonto) {
        this.creId = creId;
        this.creFechaDeposito = creFechaDeposito;
        this.creEmpresa = creEmpresa;
        this.creNombre = creNombre;
        this.creTipo = creTipo;
        this.crePrestamo = crePrestamo;
        this.creCatorcenas = creCatorcenas;
        this.creFechaPrimerPago = creFechaPrimerPago;
        this.creFechaIncobrable = creFechaIncobrable;
        this.creClaveEmpleado = creClaveEmpleado;
        this.creProducto = creProducto;
        this.creSolicitud = creSolicitud;
        this.crePagoQuincenal = crePagoQuincenal;
        this.creSaldo = creSaldo;
        this.creClave = creClave;
        this.creEstatus = creEstatus;
        this.creUsuId = creUsuId;
        this.crePadre = crePadre;
        this.creFechaNuevoMonto = creFechaNuevoMonto;
    }

   
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cre_id", nullable=false)
    public Integer getCreId() {
        return this.creId;
    }
    
    public void setCreId(Integer creId) {
        this.creId = creId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cre_fecha_deposito", length=10)
    public Date getCreFechaDeposito() {
        return this.creFechaDeposito;
    }
    
    public void setCreFechaDeposito(Date creFechaDeposito) {
        this.creFechaDeposito = creFechaDeposito;
    }

    
    @Column(name="cre_empresa", length=50)
    public String getCreEmpresa() {
        return this.creEmpresa;
    }
    
    public void setCreEmpresa(String creEmpresa) {
        this.creEmpresa = creEmpresa;
    }

    
    @Column(name="cre_nombre", length=50)
    public String getCreNombre() {
        return this.creNombre;
    }
    
    public void setCreNombre(String creNombre) {
        this.creNombre = creNombre;
    }

    
    @Column(name="cre_tipo", length=20)
    public String getCreTipo() {
        return this.creTipo;
    }
    
    public void setCreTipo(String creTipo) {
        this.creTipo = creTipo;
    }

    
    @Column(name="cre_prestamo", precision=22, scale=0)
    public Double getCrePrestamo() {
        return this.crePrestamo;
    }
    
    public void setCrePrestamo(Double crePrestamo) {
        this.crePrestamo = crePrestamo;
    }

    
    @Column(name="cre_catorcenas")
    public Integer getCreCatorcenas() {
        return this.creCatorcenas;
    }
    
    public void setCreCatorcenas(Integer creCatorcenas) {
        this.creCatorcenas = creCatorcenas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cre_fecha_primer_pago", length=10)
    public Date getCreFechaPrimerPago() {
        return this.creFechaPrimerPago;
    }
    
    public void setCreFechaPrimerPago(Date creFechaPrimerPago) {
        this.creFechaPrimerPago = creFechaPrimerPago;
    }

    
    @Column(name="cre_clave_empleado")
    public Integer getCreClaveEmpleado() {
        return this.creClaveEmpleado;
    }
    
    public void setCreClaveEmpleado(Integer creClaveEmpleado) {
        this.creClaveEmpleado = creClaveEmpleado;
    }

    
    @Column(name="cre_producto")
    public Integer getCreProducto() {
        return this.creProducto;
    }
    
    public void setCreProducto(Integer creProducto) {
        this.creProducto = creProducto;
    }

    
    @Column(name="cre_solicitud")
    public Long getCreSolicitud() {
        return this.creSolicitud;
    }
    
    public void setCreSolicitud(Long creSolicitud) {
        this.creSolicitud = creSolicitud;
    }

    
    @Column(name="cre_pago_quincenal", precision=22, scale=0)
    public Double getCrePagoQuincenal() {
        return this.crePagoQuincenal;
    }
    
    public void setCrePagoQuincenal(Double crePagoQuincenal) {
        this.crePagoQuincenal = crePagoQuincenal;
    }

    
    @Column(name="cre_saldo", precision=22, scale=0)
    public Double getCreSaldo() {
        return this.creSaldo;
    }
    
    public void setCreSaldo(Double creSaldo) {
        this.creSaldo = creSaldo;
    }

    
    @Column(name="cre_clave", length=50)
    public String getCreClave() {
        return this.creClave;
    }
    
    public void setCreClave(String creClave) {
        this.creClave = creClave;
    }

    
    @Column(name="cre_estatus")
    public Integer getCreEstatus() {
        return this.creEstatus;
    }
    
    public void setCreEstatus(Integer creEstatus) {
        this.creEstatus = creEstatus;
    }

    
    @Column(name="cre_usu_id")
    public Integer getCreUsuId() {
        return this.creUsuId;
    }
    
    public void setCreUsuId(Integer creUsuId) {
        this.creUsuId = creUsuId;
    }

    
    @Column(name="cre_padre")
    public Integer getCrePadre() {
        return this.crePadre;
    }
    
    public void setCrePadre(Integer crePadre) {
        this.crePadre = crePadre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cre_fecha_nuevo_monto", length=10)
    public Date getCreFechaNuevoMonto() {
        return this.creFechaNuevoMonto;
    }
    
    public void setCreFechaNuevoMonto(Date creFechaNuevoMonto) {
        this.creFechaNuevoMonto = creFechaNuevoMonto;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="creditosFinal")
    public Set<Amortizacion> getAmortizacions() {
        return this.amortizacions;
    }
    
    public void setAmortizacions(Set<Amortizacion> amortizacions) {
        this.amortizacions = amortizacions;
    }

    /**
     * @return the creFechaIncobrable
     */
     @Temporal(TemporalType.DATE)
    @Column(name="cre_fecha_incobrable", length=10)
    public Date getCreFechaIncobrable() {
        return creFechaIncobrable;
    }

    /**
     * @param creFechaIncobrable the creFechaIncobrable to set
     */
    public void setCreFechaIncobrable(Date creFechaIncobrable) {
        this.creFechaIncobrable = creFechaIncobrable;
    }




}


