package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PagosEstatus generated by hbm2java
 */
@Entity
@Table(name="pagos_estatus"
)
public class PagosEstatus  implements java.io.Serializable {


     private Integer pagEstId;
     private String pagEstNombre;
     private String pagEstDescripcion;

    public PagosEstatus() {
    }

    public PagosEstatus(String pagEstNombre, String pagEstDescripcion) {
       this.pagEstNombre = pagEstNombre;
       this.pagEstDescripcion = pagEstDescripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pag_est_id", unique=true, nullable=false)
    public Integer getPagEstId() {
        return this.pagEstId;
    }
    
    public void setPagEstId(Integer pagEstId) {
        this.pagEstId = pagEstId;
    }

    
    @Column(name="pag_est_nombre", nullable=false, length=30)
    public String getPagEstNombre() {
        return this.pagEstNombre;
    }
    
    public void setPagEstNombre(String pagEstNombre) {
        this.pagEstNombre = pagEstNombre;
    }

    
    @Column(name="pag_est_descripcion", nullable=false, length=200)
    public String getPagEstDescripcion() {
        return this.pagEstDescripcion;
    }
    
    public void setPagEstDescripcion(String pagEstDescripcion) {
        this.pagEstDescripcion = pagEstDescripcion;
    }




}


