package mx.com.evoti.hibernate.pojos;
// Generated 27/06/2017 11:55:25 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelBancoEdoctaId generated by hbm2java
 */
@Embeddable
public class RelBancoEdoctaId  implements java.io.Serializable {

    private static final long serialVersionUID = -8613407188217901795L;


     private long rbeId;
     private int rbeIdBancoEc;
     private int rbeTipo;

    public RelBancoEdoctaId() {
    }

    public RelBancoEdoctaId(long rbeId, int rbeIdBancoEc, int rbeTipo) {
       this.rbeId = rbeId;
       this.rbeIdBancoEc = rbeIdBancoEc;
       this.rbeTipo = rbeTipo;
    }
   


    @Column(name="rbe_id", nullable=false)
    public long getRbeId() {
        return this.rbeId;
    }
    
    public void setRbeId(long rbeId) {
        this.rbeId = rbeId;
    }


    @Column(name="rbe_id_banco_ec", nullable=false)
    public int getRbeIdBancoEc() {
        return this.rbeIdBancoEc;
    }
    
    public void setRbeIdBancoEc(int rbeIdBancoEc) {
        this.rbeIdBancoEc = rbeIdBancoEc;
    }


    @Column(name="rbe_tipo", nullable=false)
    public int getRbeTipo() {
        return this.rbeTipo;
    }
    
    public void setRbeTipo(int rbeTipo) {
        this.rbeTipo = rbeTipo;
    }


    @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelBancoEdoctaId) ) return false;
		 RelBancoEdoctaId castOther = ( RelBancoEdoctaId ) other; 
         
		 return (this.getRbeId()==castOther.getRbeId())
 && (this.getRbeIdBancoEc()==castOther.getRbeIdBancoEc())
 && (this.getRbeTipo()==castOther.getRbeTipo());
   }
   
    @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getRbeId();
         result = 37 * result + this.getRbeIdBancoEc();
         result = 37 * result + this.getRbeTipo();
         return result;
   }   


}


