package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rendimiento3 generated by hbm2java
 */
@Entity
@Table(name="rendimiento3"
)
public class Rendimiento3  implements java.io.Serializable {


     private Integer renId;
     private Date renFecha;
     private Double renInteres;
     private Double renAcumulado;
     private Double renFactor;
     private Integer renEstatus;

    public Rendimiento3() {
    }

    public Rendimiento3(Date renFecha, Double renInteres, Double renAcumulado, Double renFactor, Integer renEstatus) {
       this.renFecha = renFecha;
       this.renInteres = renInteres;
       this.renAcumulado = renAcumulado;
       this.renFactor = renFactor;
       this.renEstatus = renEstatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ren_id", nullable=false)
    public Integer getRenId() {
        return this.renId;
    }
    
    public void setRenId(Integer renId) {
        this.renId = renId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ren_fecha", length=10)
    public Date getRenFecha() {
        return this.renFecha;
    }
    
    public void setRenFecha(Date renFecha) {
        this.renFecha = renFecha;
    }

    
    @Column(name="ren_interes", precision=22, scale=0)
    public Double getRenInteres() {
        return this.renInteres;
    }
    
    public void setRenInteres(Double renInteres) {
        this.renInteres = renInteres;
    }

    
    @Column(name="ren_acumulado", precision=22, scale=0)
    public Double getRenAcumulado() {
        return this.renAcumulado;
    }
    
    public void setRenAcumulado(Double renAcumulado) {
        this.renAcumulado = renAcumulado;
    }

    
    @Column(name="ren_factor", precision=22, scale=0)
    public Double getRenFactor() {
        return this.renFactor;
    }
    
    public void setRenFactor(Double renFactor) {
        this.renFactor = renFactor;
    }

    
    @Column(name="ren_estatus")
    public Integer getRenEstatus() {
        return this.renEstatus;
    }
    
    public void setRenEstatus(Integer renEstatus) {
        this.renEstatus = renEstatus;
    }




}


