package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
)
public class Roles  implements java.io.Serializable {


     private int rolId;
     private String rolNombre;

    public Roles() {
    }

    public Roles(int rolId, String rolNombre) {
       this.rolId = rolId;
       this.rolNombre = rolNombre;
    }
   
     @Id 

    
    @Column(name="rol_id", nullable=false)
    public int getRolId() {
        return this.rolId;
    }
    
    public void setRolId(int rolId) {
        this.rolId = rolId;
    }

    
    @Column(name="rol_nombre", nullable=false, length=20)
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }




}


