package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tabulador generated by hbm2java
 */
@Entity
@Table(name="tabulador"
)
public class Tabulador  implements java.io.Serializable {


     private int tabId;
     private String tabDescripcion;
     private Double tabMensual;
     private Double tabDiario;
     private Double tabCatorcenal;

    public Tabulador() {
    }

	
    public Tabulador(int tabId) {
        this.tabId = tabId;
    }
    public Tabulador(int tabId, String tabDescripcion, Double tabMensual, Double tabDiario, Double tabCatorcenal) {
       this.tabId = tabId;
       this.tabDescripcion = tabDescripcion;
       this.tabMensual = tabMensual;
       this.tabDiario = tabDiario;
       this.tabCatorcenal = tabCatorcenal;
    }
   
     @Id 

    
    @Column(name="tab_id", nullable=false)
    public int getTabId() {
        return this.tabId;
    }
    
    public void setTabId(int tabId) {
        this.tabId = tabId;
    }

    
    @Column(name="tab_descripcion", length=75)
    public String getTabDescripcion() {
        return this.tabDescripcion;
    }
    
    public void setTabDescripcion(String tabDescripcion) {
        this.tabDescripcion = tabDescripcion;
    }

    
    @Column(name="tab_mensual", precision=22, scale=0)
    public Double getTabMensual() {
        return this.tabMensual;
    }
    
    public void setTabMensual(Double tabMensual) {
        this.tabMensual = tabMensual;
    }

    
    @Column(name="tab_diario", precision=22, scale=0)
    public Double getTabDiario() {
        return this.tabDiario;
    }
    
    public void setTabDiario(Double tabDiario) {
        this.tabDiario = tabDiario;
    }

    
    @Column(name="tab_catorcenal", precision=22, scale=0)
    public Double getTabCatorcenal() {
        return this.tabCatorcenal;
    }
    
    public void setTabCatorcenal(Double tabCatorcenal) {
        this.tabCatorcenal = tabCatorcenal;
    }




}


