package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Imagenes generated by hbm2java
 */
@Entity
@Table(name="imagenes"
)
public class Imagenes  implements java.io.Serializable {


     private Integer imaId;
     private Solicitudes solicitudes;
     private String imaImagen;
     private Integer imaTipoimagen;
     private Integer imaEstatus;
     private String imaObservaciones;

    public Imagenes() {
    }

    public Imagenes(Solicitudes solicitudes, String imaImagen, Integer imaTipoimagen, Integer imaEstatus, String imaObservaciones) {
       this.solicitudes = solicitudes;
       this.imaImagen = imaImagen;
       this.imaTipoimagen = imaTipoimagen;
       this.imaEstatus = imaEstatus;
       this.imaObservaciones = imaObservaciones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="ima_id", nullable=false)
    public Integer getImaId() {
        return this.imaId;
    }
    
    public void setImaId(Integer imaId) {
        this.imaId = imaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ima_solicitud")
    public Solicitudes getSolicitudes() {
        return this.solicitudes;
    }
    
    public void setSolicitudes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }

    
    @Column(name="ima_imagen", length=500)
    public String getImaImagen() {
        return this.imaImagen;
    }
    
    public void setImaImagen(String imaImagen) {
        this.imaImagen = imaImagen;
    }

    
    @Column(name="ima_tipoimagen")
    public Integer getImaTipoimagen() {
        return this.imaTipoimagen;
    }
    
    public void setImaTipoimagen(Integer imaTipoimagen) {
        this.imaTipoimagen = imaTipoimagen;
    }

    
    @Column(name="ima_estatus")
    public Integer getImaEstatus() {
        return this.imaEstatus;
    }
    
    public void setImaEstatus(Integer imaEstatus) {
        this.imaEstatus = imaEstatus;
    }

    
    @Column(name="ima_observaciones", length=500)
    public String getImaObservaciones() {
        return this.imaObservaciones;
    }
    
    public void setImaObservaciones(String imaObservaciones) {
        this.imaObservaciones = imaObservaciones;
    }




}


