package mx.com.evoti.hibernate.pojos;
// Generated 13/07/2019 11:50:34 PM by Hibernate Tools 4.3.1



/**
 * TipoTransaccion generated by hbm2java
 */
public class TipoTransaccion  implements java.io.Serializable {


     private int tipoTranId;
     private String tipoTran;
     private String tipoTranDescripcion;

    public TipoTransaccion() {
    }

	
    public TipoTransaccion(int tipoTranId) {
        this.tipoTranId = tipoTranId;
    }
    public TipoTransaccion(int tipoTranId, String tipoTran, String tipoTranDescripcion) {
       this.tipoTranId = tipoTranId;
       this.tipoTran = tipoTran;
       this.tipoTranDescripcion = tipoTranDescripcion;
    }
   
    public int getTipoTranId() {
        return this.tipoTranId;
    }
    
    public void setTipoTranId(int tipoTranId) {
        this.tipoTranId = tipoTranId;
    }
    public String getTipoTran() {
        return this.tipoTran;
    }
    
    public void setTipoTran(String tipoTran) {
        this.tipoTran = tipoTran;
    }
    public String getTipoTranDescripcion() {
        return this.tipoTranDescripcion;
    }
    
    public void setTipoTranDescripcion(String tipoTranDescripcion) {
        this.tipoTranDescripcion = tipoTranDescripcion;
    }




}


