package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitudes generated by hbm2java
 */
@Entity
@Table(name="solicitudes" 
)
public class Solicitudes  implements java.io.Serializable {


     private Long solId;
     private Productos productos;
     private SolicitudEstatus solicitudEstatus;
     private Usuarios usuarios;
     private Integer solClaveEmpleado;
     private Double solSueldoNeto;
     private Double solDeducciones;
     private Double solMontoSolicitado;
     private Integer solCatorcenas;
     private Double solPagoCredito;
     private String solBanco;
     private String solNumeroCuenta;
     private String solClabeInterbancaria;
     private String solReferencia;
     private String solNombreTarjetahabiente;
     private String solAseguradora;
     private String solNoPoliza;
     private Double solPagoTotal;
     private Double solAguinaldo;
     private Double solFa;
     private Double solIntereses;
     private String solObservacion;
     private Date solFechaUltCatorcena;
     private Date solFechaAutorizacion;
     private Date solFechaCreacion;
     private Date solFechaCancelacion;
     private Date solFechaFondeo;
     private Date solFechaEnviodocumentos;
     private Integer solFacatorcena;
     private Date solFechaDeposito;
     private String solMotivoRechazo;
     private Integer solEstatusDb;
     private Integer solFormatoDocFirmada;
     private Set<SolicitudAvales> solicitudAvaleses = new HashSet<SolicitudAvales>(0);
     private Set<Imagenes> imageneses = new HashSet<Imagenes>(0);

    public Solicitudes() {
    }

	
    public Solicitudes(Productos productos, SolicitudEstatus solicitudEstatus, Usuarios usuarios) {
        this.productos = productos;
        this.solicitudEstatus = solicitudEstatus;
        this.usuarios = usuarios;
    }
    public Solicitudes(Productos productos, SolicitudEstatus solicitudEstatus, Usuarios usuarios, Integer solClaveEmpleado, Double solSueldoNeto, Double solDeducciones, Double solMontoSolicitado, Integer solCatorcenas, Double solPagoCredito, String solBanco, String solNumeroCuenta, String solClabeInterbancaria, String solNombreTarjetahabiente, Double solPagoTotal, Double solAguinaldo, Double solFa, Double solIntereses, String solObservacion, Date solFechaUltCatorcena, Date solFechaAutorizacion, Date solFechaCreacion, Date solFechaCancelacion, Date solFechaFondeo, Date solFechaEnviodocumentos, Integer solFacatorcena, Date solFechaDeposito, String solMotivoRechazo, Integer solEstatusDb, Integer solFormatoDocFirmada, Set<SolicitudAvales> solicitudAvaleses, Set<Imagenes> imageneses) {
       this.productos = productos;
       this.solicitudEstatus = solicitudEstatus;
       this.usuarios = usuarios;
       this.solClaveEmpleado = solClaveEmpleado;
       this.solSueldoNeto = solSueldoNeto;
       this.solDeducciones = solDeducciones;
       this.solMontoSolicitado = solMontoSolicitado;
       this.solCatorcenas = solCatorcenas;
       this.solPagoCredito = solPagoCredito;
       this.solBanco = solBanco;
       this.solNumeroCuenta = solNumeroCuenta;
       this.solClabeInterbancaria = solClabeInterbancaria;
       this.solNombreTarjetahabiente = solNombreTarjetahabiente;
       this.solPagoTotal = solPagoTotal;
       this.solAguinaldo = solAguinaldo;
       this.solFa = solFa;
       this.solIntereses = solIntereses;
       this.solObservacion = solObservacion;
       this.solFechaUltCatorcena = solFechaUltCatorcena;
       this.solFechaAutorizacion = solFechaAutorizacion;
       this.solFechaCreacion = solFechaCreacion;
       this.solFechaCancelacion = solFechaCancelacion;
       this.solFechaFondeo = solFechaFondeo;
       this.solFechaEnviodocumentos = solFechaEnviodocumentos;
       this.solFacatorcena = solFacatorcena;
       this.solFechaDeposito = solFechaDeposito;
       this.solMotivoRechazo = solMotivoRechazo;
       this.solEstatusDb = solEstatusDb;
       this.solFormatoDocFirmada = solFormatoDocFirmada;
       this.solicitudAvaleses = solicitudAvaleses;
       this.imageneses = imageneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sol_id", nullable=false)
    public Long getSolId() {
        return this.solId;
    }
    
    public void setSolId(Long solId) {
        this.solId = solId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sol_producto", nullable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sol_estatus", nullable=false)
    public SolicitudEstatus getSolicitudEstatus() {
        return this.solicitudEstatus;
    }
    
    public void setSolicitudEstatus(SolicitudEstatus solicitudEstatus) {
        this.solicitudEstatus = solicitudEstatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sol_usu_id", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="sol_clave_empleado")
    public Integer getSolClaveEmpleado() {
        return this.solClaveEmpleado;
    }
    
    public void setSolClaveEmpleado(Integer solClaveEmpleado) {
        this.solClaveEmpleado = solClaveEmpleado;
    }

    
    @Column(name="sol_sueldo_neto", precision=22, scale=0)
    public Double getSolSueldoNeto() {
        return this.solSueldoNeto;
    }
    
    public void setSolSueldoNeto(Double solSueldoNeto) {
        this.solSueldoNeto = solSueldoNeto;
    }

    
    @Column(name="sol_deducciones", precision=22, scale=0)
    public Double getSolDeducciones() {
        return this.solDeducciones;
    }
    
    public void setSolDeducciones(Double solDeducciones) {
        this.solDeducciones = solDeducciones;
    }

    
    @Column(name="sol_monto_solicitado", precision=22, scale=0)
    public Double getSolMontoSolicitado() {
        return this.solMontoSolicitado;
    }
    
    public void setSolMontoSolicitado(Double solMontoSolicitado) {
        this.solMontoSolicitado = solMontoSolicitado;
    }

    
    @Column(name="sol_catorcenas")
    public Integer getSolCatorcenas() {
        return this.solCatorcenas;
    }
    
    public void setSolCatorcenas(Integer solCatorcenas) {
        this.solCatorcenas = solCatorcenas;
    }

    
    @Column(name="sol_pago_credito", precision=22, scale=0)
    public Double getSolPagoCredito() {
        return this.solPagoCredito;
    }
    
    public void setSolPagoCredito(Double solPagoCredito) {
        this.solPagoCredito = solPagoCredito;
    }

    
    @Column(name="sol_banco", length=50)
    public String getSolBanco() {
        return this.solBanco;
    }
    
    public void setSolBanco(String solBanco) {
        this.solBanco = solBanco;
    }

    
    @Column(name="sol_numero_cuenta", length=50)
    public String getSolNumeroCuenta() {
        return this.solNumeroCuenta;
    }
    
    public void setSolNumeroCuenta(String solNumeroCuenta) {
        this.solNumeroCuenta = solNumeroCuenta;
    }

    
    @Column(name="sol_clabe_interbancaria", length=50)
    public String getSolClabeInterbancaria() {
        return this.solClabeInterbancaria;
    }
    
    public void setSolClabeInterbancaria(String solClabeInterbancaria) {
        this.solClabeInterbancaria = solClabeInterbancaria;
    }

    
    @Column(name="sol_nombre_tarjetahabiente", length=50)
    public String getSolNombreTarjetahabiente() {
        return this.solNombreTarjetahabiente;
    }
    
    public void setSolNombreTarjetahabiente(String solNombreTarjetahabiente) {
        this.solNombreTarjetahabiente = solNombreTarjetahabiente;
    }

    
    @Column(name="sol_pago_total", precision=22, scale=0)
    public Double getSolPagoTotal() {
        return this.solPagoTotal;
    }
    
    public void setSolPagoTotal(Double solPagoTotal) {
        this.solPagoTotal = solPagoTotal;
    }

    
    @Column(name="sol_aguinaldo", precision=22, scale=0)
    public Double getSolAguinaldo() {
        return this.solAguinaldo;
    }
    
    public void setSolAguinaldo(Double solAguinaldo) {
        this.solAguinaldo = solAguinaldo;
    }

    
    @Column(name="sol_fa", precision=22, scale=0)
    public Double getSolFa() {
        return this.solFa;
    }
    
    public void setSolFa(Double solFa) {
        this.solFa = solFa;
    }

    
    @Column(name="sol_intereses", precision=22, scale=0)
    public Double getSolIntereses() {
        return this.solIntereses;
    }
    
    public void setSolIntereses(Double solIntereses) {
        this.solIntereses = solIntereses;
    }

    
    @Column(name="sol_observacion", length=200)
    public String getSolObservacion() {
        return this.solObservacion;
    }
    
    public void setSolObservacion(String solObservacion) {
        this.solObservacion = solObservacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sol_fecha_ult_catorcena", length=10)
    public Date getSolFechaUltCatorcena() {
        return this.solFechaUltCatorcena;
    }
    
    public void setSolFechaUltCatorcena(Date solFechaUltCatorcena) {
        this.solFechaUltCatorcena = solFechaUltCatorcena;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sol_fecha_autorizacion", length=10)
    public Date getSolFechaAutorizacion() {
        return this.solFechaAutorizacion;
    }
    
    public void setSolFechaAutorizacion(Date solFechaAutorizacion) {
        this.solFechaAutorizacion = solFechaAutorizacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sol_fecha_creacion", length=10)
    public Date getSolFechaCreacion() {
        return this.solFechaCreacion;
    }
    
    public void setSolFechaCreacion(Date solFechaCreacion) {
        this.solFechaCreacion = solFechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sol_fecha_cancelacion", length=10)
    public Date getSolFechaCancelacion() {
        return this.solFechaCancelacion;
    }
    
    public void setSolFechaCancelacion(Date solFechaCancelacion) {
        this.solFechaCancelacion = solFechaCancelacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sol_fecha_fondeo", length=10)
    public Date getSolFechaFondeo() {
        return this.solFechaFondeo;
    }
    
    public void setSolFechaFondeo(Date solFechaFondeo) {
        this.solFechaFondeo = solFechaFondeo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sol_fecha_enviodocumentos", length=10)
    public Date getSolFechaEnviodocumentos() {
        return this.solFechaEnviodocumentos;
    }
    
    public void setSolFechaEnviodocumentos(Date solFechaEnviodocumentos) {
        this.solFechaEnviodocumentos = solFechaEnviodocumentos;
    }

    
    @Column(name="sol_facatorcena")
    public Integer getSolFacatorcena() {
        return this.solFacatorcena;
    }
    
    public void setSolFacatorcena(Integer solFacatorcena) {
        this.solFacatorcena = solFacatorcena;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sol_fecha_deposito", length=10)
    public Date getSolFechaDeposito() {
        return this.solFechaDeposito;
    }
    
    public void setSolFechaDeposito(Date solFechaDeposito) {
        this.solFechaDeposito = solFechaDeposito;
    }

    
    @Column(name="sol_motivo_rechazo", length=150)
    public String getSolMotivoRechazo() {
        return this.solMotivoRechazo;
    }
    
    public void setSolMotivoRechazo(String solMotivoRechazo) {
        this.solMotivoRechazo = solMotivoRechazo;
    }

    
    @Column(name="sol_estatus_db")
    public Integer getSolEstatusDb() {
        return this.solEstatusDb;
    }
    
    public void setSolEstatusDb(Integer solEstatusDb) {
        this.solEstatusDb = solEstatusDb;
    }

@OneToMany(cascade=CascadeType.PERSIST, fetch=FetchType.LAZY, mappedBy="solicitudes")
    public Set<SolicitudAvales> getSolicitudAvaleses() {
        return this.solicitudAvaleses;
    }
    
    public void setSolicitudAvaleses(Set<SolicitudAvales> solicitudAvaleses) {
        this.solicitudAvaleses = solicitudAvaleses;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="solicitudes")
    public Set<Imagenes> getImageneses() {
        return this.imageneses;
    }
    
    public void setImageneses(Set<Imagenes> imageneses) {
        this.imageneses = imageneses;
    }

    /**
     * @return the solFormatoDocFirmada
     */
    @Column(name="sol_formato_doc_firmada")
    public Integer getSolFormatoDocFirmada() {
        return solFormatoDocFirmada;
    }

    /**
     * @param solFormatoDocFirmada the solFormatoDocFirmada to set
     */
    public void setSolFormatoDocFirmada(Integer solFormatoDocFirmada) {
        this.solFormatoDocFirmada = solFormatoDocFirmada;
    }

    /**
     * @return the solReferencia
     */
     @Column(name="sol_referencia", length=50)
    public String getSolReferencia() {
        return solReferencia;
    }

    /**
     * @param solReferencia the solReferencia to set
     */
    public void setSolReferencia(String solReferencia) {
        this.solReferencia = solReferencia;
    }

    /**
     * @return the solAseguradora
     */
     @Column(name="sol_aseguradora", length=50)
    public String getSolAseguradora() {
        return solAseguradora;
    }

    /**
     * @param solAseguradora the solAseguradora to set
     */
    public void setSolAseguradora(String solAseguradora) {
        this.solAseguradora = solAseguradora;
    }

    /**
     * @return the solNoPoliza
     */
     @Column(name="sol_no_poliza", length=50)
    public String getSolNoPoliza() {
        return solNoPoliza;
    }

    /**
     * @param solNoPoliza the solNoPoliza to set
     */
    public void setSolNoPoliza(String solNoPoliza) {
        this.solNoPoliza = solNoPoliza;
    }




}


