package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SolicitudEstatus generated by hbm2java
 */
@Entity
@Table(name="solicitud_estatus"
)
public class SolicitudEstatus  implements java.io.Serializable {


     private int solEstId;
     private String solEstNmbrEst;
     private String solEstDescripcion;
     private Set<Solicitudes> solicitudeses = new HashSet<Solicitudes>(0);

    public SolicitudEstatus() {
    }

    public SolicitudEstatus(int solEstId) {
        this.solEstId = solEstId;
    }

	
    public SolicitudEstatus(int solEstId, String solEstNmbrEst, String solEstDescripcion) {
        this.solEstId = solEstId;
        this.solEstNmbrEst = solEstNmbrEst;
        this.solEstDescripcion = solEstDescripcion;
    }
    public SolicitudEstatus(int solEstId, String solEstNmbrEst, String solEstDescripcion, Set<Solicitudes> solicitudeses) {
       this.solEstId = solEstId;
       this.solEstNmbrEst = solEstNmbrEst;
       this.solEstDescripcion = solEstDescripcion;
       this.solicitudeses = solicitudeses;
    }
   
     @Id 

    
    @Column(name="sol_est_id", nullable=false)
    public int getSolEstId() {
        return this.solEstId;
    }
    
    public void setSolEstId(int solEstId) {
        this.solEstId = solEstId;
    }

    
    @Column(name="sol_est_nmbr_est", nullable=false, length=20)
    public String getSolEstNmbrEst() {
        return this.solEstNmbrEst;
    }
    
    public void setSolEstNmbrEst(String solEstNmbrEst) {
        this.solEstNmbrEst = solEstNmbrEst;
    }

    
    @Column(name="sol_est_descripcion", nullable=false, length=100)
    public String getSolEstDescripcion() {
        return this.solEstDescripcion;
    }
    
    public void setSolEstDescripcion(String solEstDescripcion) {
        this.solEstDescripcion = solEstDescripcion;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="solicitudEstatus")
    public Set<Solicitudes> getSolicitudeses() {
        return this.solicitudeses;
    }
    
    public void setSolicitudeses(Set<Solicitudes> solicitudeses) {
        this.solicitudeses = solicitudeses;
    }




}


