package mx.com.evoti.hibernate.pojos;
// Generated 1/02/2017 05:08:41 PM by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ParentescoBen generated by hbm2java
 */
@Entity
@Table(name="parentesco_ben"
)
public class ParentescoBen  implements java.io.Serializable {


     private Integer parId;
     private String parNombre;

    public ParentescoBen() {
    }

    public ParentescoBen(String parNombre) {
       this.parNombre = parNombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="par_id", unique=true, nullable=false)
    public Integer getParId() {
        return this.parId;
    }
    
    public void setParId(Integer parId) {
        this.parId = parId;
    }

    
    @Column(name="par_nombre", length=20)
    public String getParNombre() {
        return this.parNombre;
    }
    
    public void setParNombre(String parNombre) {
        this.parNombre = parNombre;
    }


@Override
    public String toString() {
        return parId+"-"+parNombre;
    }

    
    
      @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ParentescoBen other = (ParentescoBen) obj;
        if (!Objects.equals(this.parNombre, other.parNombre)) {
            return false;
        }
        if (!Objects.equals(this.parId, other.parId)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 67 * hash + Objects.hashCode(this.parId);
        hash = 67 * hash + Objects.hashCode(this.parNombre);
        return hash;
    }

}


