package mx.com.evoti.hibernate.pojos;
// Generated 16/01/2017 04:22:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bitacora generated by hbm2java
 */
@Entity
@Table(name="bitacora"
)
public class Bitacora  implements java.io.Serializable {


     private int bitId;
     private int bitTipo;
     private String bitTitulo;
     private String bitNota;
     private Date bitFecha;
     private int bitUsuario;
     private Long bitReferencia;
     private Long bitSubreferencia;

    public Bitacora() {
    }

	
    public Bitacora(int bitId, int bitTipo, int bitUsuario, Long bitReferencia) {
        this.bitId = bitId;
        this.bitTipo = bitTipo;
        this.bitUsuario = bitUsuario;
        this.bitReferencia = bitReferencia;
    }
    public Bitacora(int bitId, int bitTipo, String bitNota, Date bitFecha, int bitUsuario, Long bitReferencia, Long bitSubreferencia) {
       this.bitId = bitId;
       this.bitTipo = bitTipo;
       this.bitNota = bitNota;
       this.bitFecha = bitFecha;
       this.bitUsuario = bitUsuario;
       this.bitReferencia = bitReferencia;
       this.bitSubreferencia = bitSubreferencia;
    }
   
 @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="bit_id", unique=true, nullable=false)
    public int getBitId() {
        return this.bitId;
    }
    
    public void setBitId(int bitId) {
        this.bitId = bitId;
    }

    
    @Column(name="bit_tipo", nullable=false)
    public int getBitTipo() {
        return this.bitTipo;
    }
    
    public void setBitTipo(int bitTipo) {
        this.bitTipo = bitTipo;
    }

    
    @Column(name="bit_nota", length=500)
    public String getBitNota() {
        return this.bitNota;
    }
    
    public void setBitNota(String bitNota) {
        this.bitNota = bitNota;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bit_fecha", length=10)
    public Date getBitFecha() {
        return this.bitFecha;
    }
    
    public void setBitFecha(Date bitFecha) {
        this.bitFecha = bitFecha;
    }

    
    @Column(name="bit_usuario", nullable=false)
    public int getBitUsuario() {
        return this.bitUsuario;
    }
    
    public void setBitUsuario(int bitUsuario) {
        this.bitUsuario = bitUsuario;
    }

    
    @Column(name="bit_referencia", nullable=false)
    public Long getBitReferencia() {
        return this.bitReferencia;
    }
    
    public void setBitReferencia(Long bitReferencia) {
        this.bitReferencia = bitReferencia;
    }

    
    @Column(name="bit_subreferencia")
    public Long getBitSubreferencia() {
        return this.bitSubreferencia;
    }
    
    public void setBitSubreferencia(Long bitSubreferencia) {
        this.bitSubreferencia = bitSubreferencia;
    }

    /**
     * @return the bitTitulo
     */
     @Column(name="bit_titulo", length=500)
    public String getBitTitulo() {
        return bitTitulo;
    }

    /**
     * @param bitTitulo the bitTitulo to set
     */
    public void setBitTitulo(String bitTitulo) {
        this.bitTitulo = bitTitulo;
    }




}


