package mx.com.evoti.hibernate.pojos;
// Generated 21/10/2016 12:57:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bancos generated by hbm2java
 */
@Entity
@Table(name="bancos"
)
public class Bancos  implements java.io.Serializable {


     private Integer banId;
     private Integer banConcepto;
     private Integer banIdConceptoSistema;
     private Integer banAjustado;
     private double banMonto;
     private int banEmpresa;
     private Date banFechatransaccion;
     private Date banFechaRelacion;
     private Long banIdRelacion;

    public Bancos() {
    }

    public Bancos(Integer banId, Integer banConcepto, Integer banIdConceptoSistema, Integer banAjustado, double banMonto, int banEmpresa, Date banFechatransaccion, Date banFechaRelacion, Long banIdRelacion) {
        this.banId = banId;
        this.banConcepto = banConcepto;
        this.banIdConceptoSistema = banIdConceptoSistema;
        this.banAjustado = banAjustado;
        this.banMonto = banMonto;
        this.banEmpresa = banEmpresa;
        this.banFechatransaccion = banFechatransaccion;
        this.banFechaRelacion = banFechaRelacion;
        this.banIdRelacion = banIdRelacion;
    }

   

    
    
   
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ban_id", nullable=false)
    public Integer getBanId() {
        return this.banId;
    }
    
    public void setBanId(Integer banId) {
        this.banId = banId;
    }

    
    @Column(name="ban_concepto", nullable=false)
    public Integer getBanConcepto() {
        return this.banConcepto;
    }
    
    public void setBanConcepto(Integer banConcepto) {
        this.banConcepto = banConcepto;
    }

    
    @Column(name="ban_monto", nullable=false, precision=22, scale=0)
    public double getBanMonto() {
        return this.banMonto;
    }
    
    public void setBanMonto(double banMonto) {
        this.banMonto = banMonto;
    }

    
    @Column(name="ban_empresa")
    public int getBanEmpresa() {
        return this.banEmpresa;
    }
    
    public void setBanEmpresa(int banEmpresa) {
        this.banEmpresa = banEmpresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ban_fechatransaccion")
    public Date getBanFechatransaccion() {
        return this.banFechatransaccion;
    }
    
    public void setBanFechatransaccion(Date banFechatransaccion) {
        this.banFechatransaccion = banFechatransaccion;
    }

    /**
     * @return the banIdConceptoSistema
     */
    @Column(name="ban_id_concepto_sistema", nullable=false)
    public Integer getBanIdConceptoSistema() {
        return banIdConceptoSistema;
    }

    /**
     * @param banIdConceptoSistema the banIdConceptoSistema to set
     */
    public void setBanIdConceptoSistema(Integer banIdConceptoSistema) {
        this.banIdConceptoSistema = banIdConceptoSistema;
    }

    /**
     * @return the banAjustado
     */
     @Column(name="ban_ajustado", nullable=false)
    public Integer getBanAjustado() {
        return banAjustado;
    }

    /**
     * @param banAjustado the banAjustado to set
     */
    public void setBanAjustado(Integer banAjustado) {
        this.banAjustado = banAjustado;
    }

    /**
     * @return the banFechaRelacion
     */
     @Temporal(TemporalType.DATE)
     @Column(name="ban_fecha_relacion")
    public Date getBanFechaRelacion() {
        return banFechaRelacion;
    }

    /**
     * @param banFechaRelacion the banFechaRelacion to set
     */
    public void setBanFechaRelacion(Date banFechaRelacion) {
        this.banFechaRelacion = banFechaRelacion;
    }

    /**
     * @return the banIdRelacion
     */
     @Column(name="ban_id_relacion")
    public Long getBanIdRelacion() {
        return banIdRelacion;
    }

    /**
     * @param banIdRelacion the banIdRelacion to set
     */
    public void setBanIdRelacion(Long banIdRelacion) {
        this.banIdRelacion = banIdRelacion;
    }




}


